name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17 and Maven
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: maven
        
    - name: Install Maven manually
      run: |
        MAVEN_VERSION=3.9.6
        echo "M2_HOME=/opt/maven" >> $GITHUB_ENV
        echo "PATH=/opt/maven/bin:$PATH" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn clean install

    - name: Copy build artifact
      run: |
        mkdir -p /tmp/myapps
        cp target/*.jar /tmp/myapps/app.jar

    - name: Make deploy script executable
      run: chmod +x deploy.sh

    - name: Run deploy script
      run: ./deploy.sh
